/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XButton: typeof import('./components/XButton/XButton.vue')['default']
    XDialog: typeof import('./components/XDialog/XDialog.vue')['default']
    XForm: typeof import('./components/XForm/XForm.vue')['default']
    XFormItem: typeof import('./components/XForm/XFormItem.vue')['default']
    XInput: typeof import('./components/XInput/XInput.vue')['default']
    XMessage: typeof import('./components/XMessage/XMessage.vue')['default']
    XPagination: typeof import('./components/XPagination/XPagination.vue')['default']
    XTable: typeof import('./components/XTable/XTable.vue')['default']
  }
}
